### POST: /access/sign-in
POST http://localhost:8080/api/v1/access/sign-in HTTP/1.1
content-type: application/json

{
    "credLogin": "nguyenhuy7402@gmail.com",
    "credPassword" : "Nnh_2002"
}

### POST: /access/sign-out
POST http://localhost:8080/api/v1/access/sign-out HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzEyN2MwZjQyY2ZjZmEwZjQ0NTc5NjIiLCJFbWFpbCI6Im5ndXllbmh1eTc0MDJAZ21haWwuY29tIiwiTW9iaWxlUGhvbmUiOiIwOTM1NTg4NzcxIiwiRmlyc3ROYW1lIjoiU3R1ZmYiLCJMYXN0TmFtZSI6IlN0b3JlIiwiQXZhdGFyIjpudWxsLCJBYm91dCI6bnVsbCwiSXNWZXJpZmllZCI6dHJ1ZSwiSXNCbG9ja2VkIjpmYWxzZSwiSXNCYW5uZWQiOmZhbHNlLCJSb2xlcyI6WyI2NzEyN2MwNTEwYjBmYzA4OTU1NzAzNTAiXSwiX192IjowLCJpYXQiOjE3MjkyNjQ3MDQsImV4cCI6MTcyOTI2NTAwNH0.FGApKQkMp2KuQ2eT8JYdYPM2L2A6KIdV5GMksWNArKiDtirW78ekxm14dOcpBSnDb3ZnQaAAZ5jzNuGxqeEGgZbigBo4fYKICCU8w5nbdhFAh5MJKZfhWPURVTk4DZOL6KxybTBg4KChOwrnkj_LgfKLMzHT4KeTxCYTnlsgO804PLBRjfFZ7m_tSEOu5kyKo38AHYifvWiTwoN4oARUKKikpMXK81VslxkrPYU_sCPM4kj0j0bIdX_Sm_bToZd2tz4mWibdoba2S-xH7tBuqF-Dshm7Zz2DzLreRbE9A9g6-U41i2eqYQxq7tGDyxUJRvYDugAsoyvYG9kvFhHMNQ
x-client-id: 67127c0f42cfcfa0f4457962
x-refresh-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uIjoiNjcxMjdjNDA0MmNmY2ZhMGY0NDU3OTc3IiwiaWF0IjoxNzI5MjY0NzA0LCJleHAiOjE3MjkyNjY1MDR9.dpVbTFFwm1yfro4QfX94nKMg2EHCuuDErlAiL_yGBPIEt78gIJ690Cu2D56yBvkvEp8-Y3bknxMRRebpd41OMtLp_HdQgMFVw3fgiv9L4JNEYRSQFzekNE96H_2coGqHMKfYH6GG9iymQV8Q3Hc8OCdScNG5vHX17Ku01IkIjmTJiSzaWHXGFKywNUDmGyntAHK7SJRJXvyOq7g2-mltJmn18PPTNtp-ahO1IvXbX59Ef5K9CVCjb9TmDOjjkcsn4MTwUDDxW5LR95Bi50McbZETKeKguI9ocJrQtlBAnjSHqes4CTaP35UvOsP8Yn9MtIp1O151NbNTZW1PA6dHug

### POST: /access/refresh
POST http://localhost:8080/api/v1/access/refresh HTTP/1.1
content-type: application/json
x-client-id: 67127c0f42cfcfa0f4457962
x-refresh-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uIjoiNjcxMjdmNWE3MTg2NDBiYTQxODQ4MzJlIiwiaWF0IjoxNzI5MjY1NDk4LCJleHAiOjE3MjkyNjcyOTh9.boUgTfJyvp2EYez_kKJPaoQjJwASEhRru072l1JK8oQKrosPwMY96KAveq1hi8tR8FfjG5RyEq8vtECBs8NQojxIUp3BW8COr5X39OiaZ-9XYY4JoWnSI8_Q8YfA-55SYdDjJmZRpKuwE5Pabas2rZWFs3_HbDYhL47-_DthjatU9tx9ZyEh9KFI9MJAe672iTmnwhlALA15P6H512WMULjXNSDpX9t-u38DkJm2DDaY6gA9wnhigxeiJWbkyw_45X8HwD-xQo8TWYdRrl-F0A-DoJd0T8JOzAh-AxwVjgj3ZtQJ5hU_O4BInHSpHUwleFBopVoKgMCOJXzBtypEYg


