### POST: /sellers/register
POST http://localhost:8080/api/v1/sellers/register HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzEyN2MwZjQyY2ZjZmEwZjQ0NTc5NjIiLCJFbWFpbCI6Im5ndXllbmh1eTc0MDJAZ21haWwuY29tIiwiTW9iaWxlUGhvbmUiOiIwOTM1NTg4NzcxIiwiRmlyc3ROYW1lIjoiU3R1ZmYiLCJMYXN0TmFtZSI6IlN0b3JlIiwiQXZhdGFyIjpudWxsLCJBYm91dCI6bnVsbCwiSXNWZXJpZmllZCI6dHJ1ZSwiSXNCbG9ja2VkIjpmYWxzZSwiSXNCYW5uZWQiOmZhbHNlLCJSb2xlcyI6WyI2NzEyN2MwNTEwYjBmYzA4OTU1NzAzNTAiXSwiX192IjowLCJpYXQiOjE3MjkyNjY1NDYsImV4cCI6MTcyOTI2Njg0Nn0.NjIjjhoGPwuAY5AuBmhb0_x9U9oeWJMKdD8AySDI5p5E-KXtakvSLDjxs7F5V6Cny3l282s-VTRyslprjTj4UuGWDUYBKHP2OYDMvesfUMxFe-raeK7LSAJ7JrXl80WVeUFgGeHZCnvC5SoXVOaJqMdNJBYD_z6SPTPolzLjpiRH1uGaoac1cOw0BZ0mICHHa8fKw_GcvpF12qLnx-MBAsD0WsgczAmRFWtjgRFYDtqeumdUSthN34FPl2_SZzip7Bv9xqCFjd_TXvUQs-tyh41PANUq8RsOmxAQFja8u958uShTt2gSs3OtJskfUVBToXW55Uwb_ABRprIY9XUEpw
x-client-id: 67127c0f42cfcfa0f4457962

