### POST: /users/request-verify-email
POST http://localhost:8080/api/v1/users/request-verify-email HTTP/1.1
content-type: application/json

{
    "email": "nguyenhuy7402@gmail.com"
}

### POST: /users/verify-email
POST http://localhost:8080/api/v1/users/verify-email HTTP/1.1
content-type: application/json

{
    "email": "nguyenhuy7402@gmail.com",
    "otp": "164883"
}

### POST: /users/
POST http://localhost:8080/api/v1/users HTTP/1.1
content-type: application/json

{
    "email": "nguyenhuy7402@gmail.com",
    "mobilePhone": "0935588771", 
    "firstName": "Stuff",
    "lastName": "Store", 
    "credPassword" : "Store@2024",
    "passwordConfirmation" : "Store@2024"
}